### ISSUE TITLE
Date-based option for Late bookings

### ISSUE THREAD

**Issue by crysttn** [NateWr/restaurant-reservations#78] opened 2016-10-19 15:50 UTC
Hi Nate,

First of all, awesome job on keeping up the good work on this plugin.

I see that the way you've set up the "at least 1 day in advance" option for late booking is strictly 1440 minutes (24 hours), but that's not working for how restaurants usually work.

Can you make it based on date instead of minutes? Because if it's 10 PM, I should be able to make a reservation for tomorrow at 6 PM, the case of which is not possible at the moment.

I look forward to hearing from you.
Cheers,
Crys

**Comment by NateWr** [comment] 2016-10-20 09:53
Hi Crys,

I get this request from time to time and I've considered exploring a solution in #63. I'm going to close this issue as a duplicate of that issue.

I probably won't adjust the existing behaviour based on minutes, because it would unexpectedly change how the plugin works for thousands of existing users. I'd probably go with a new option like "Block same-day bookings" which would work in the way you describe.

**Closed by NateWr** 2016-10-20 09:53 UTC
